sudo: required

language: generic

services:
  - docker

before_install:
  - echo "start Creating an image with dockerfile"
  - docker build -t hllee1021/docekr-react-app -f Dockerfile.dev Dockerfile.dev .

script:
  - docker run -e CI=true hllee1021/docekr-react-app npm run test -- --coverage

after_success:
  - echo "Test Success"